clothing:
  data_path: './datasets'
  batch_size_train: 128
  batch_size_test: 128
  embedding_sizes: 64
  lr: 1.0e-3
  epochs: 30
  test_interval: 5
  bundle_size: 10
  sep: "\t"
  file_type: ".txt"


electronic:
  data_path: './datasets'
  batch_size_train: 128
  batch_size_test: 128
  embedding_sizes: 64
  lr: 1.0e-3
  epochs: 30
  test_interval: 5
  bundle_size: 10
  sep: "\t"
  file_type: ".txt"


food:
  data_path: './datasets'
  batch_size_train: 128
  batch_size_test: 128
  embedding_sizes: 64
  lr: 1.0e-3
  epochs: 30
  test_interval: 5
  bundle_size: 10
  sep: "\t"
  file_type: ".txt"
